name: MinGW-CI

on: push

jobs:
  windows-mingw:
    name: ${{ matrix.mingw }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mingw: ["MINGW32", "MINGW64"]
        include:
          - mingw: "MINGW32"
            package: "mingw-w64-i686"
          - mingw: "MINGW64"
            package: "mingw-w64-x86_64"

    env:
      MSYSTEM: ${{ matrix.mingw }}
      CHERE_INVOKING: 1
      CMAKE_ARGS: -DSIMDJSON_BUILD_STATIC=ON
      CMAKE_GENERATOR: MSYS Makefiles

    steps:
      - uses: actions/checkout@v2

      - name: Compiler
        run: |
          gcc --version
          g++ --version

      - name: Build
        run: |
          cmake --build . --verbose
          ctest -j4 --output-on-failure -E checkperf
          cmake --build . --verbose
          
      - name: Test
        run: |
          ctest -j4 --output-on-failure -E checkperf
