name: MinGW-CI

on: push

jobs:
  windows-mingw:
    name: ${{ matrix.mingw }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mingw: ["MINGW32", "MINGW64"]
        include:
          - mingw: "MINGW32"
          - mingw: "MINGW64"

    env:
      CMAKE_GENERATOR: MSYS Makefiles

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v1
        with:
          update: true
          # cache: true
          msystem: ${{ matrix.mingw }}

      - name: Compiler
        run: |
          gcc --version
          g++ --version

      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake -DSIMDJSON_BUILD_STATIC=ON  -DSIMDJSON_COMPETITION=OFF # -DSIMDJSON_GOOGLE_BENCHMARKS=OFF # -DSIMDJSON_ENABLE_THREADS=OFF  # -DSIMDJSON_DO_NOT_USE_THREADS_NO_MATTER_WHAT=ON ..
          cmake --build . --verbose
          ctest -j4 --output-on-failure -E checkperf
