name: MinGW-CI

on: push

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      CMAKE_GENERATOR: Ninja # critical

    strategy:
      fail-fast: false
      matrix:
        name: [windows-gcc]

        include:
          - name: windows-gcc
            os: windows-2016
            compiler: gcc

    steps:
      - uses: actions/checkout@v2

      - name: Install Ninja
        shell: powershell
        run: |
          choco install -y ninja --force              # critical

      - name: Build 64-bit
        run: |
          mkdir buildx64
          cd buildx64
          cmake -DSIMDJSON_BUILD_STATIC=ON -SIMDJSON_DO_NOT_USE_THREADS_NO_MATTER_WHAT=1 ..
          cmake --build . --verbose
          cd ..

      - name: Test 64-bit
        run: |
          cd buildx64
          ctest -j4 --output-on-failure -E checkperf
          cd ..

      - name: Uninstall MinGW and Ninja, Install MinGW 32-bit and Reinstall Ninja
        shell: powershell
        run: |
          choco uninstall mingw
          choco uninstall ninja

          choco install -y mingw -x86 --force
          choco install -y ninja --force
      
      - name: Build 32-bit
        run: |
          mkdir buildx86
          cd buildx86
          cmake -DSIMDJSON_BUILD_STATIC=ON ..
          cmake --build . --verbose
          cd ..

      - name: Test 32-bit
        run: |
          cd buildx86
          ctest -j4 --output-on-failure -E checkperf