name: MinGW-CI

on: push

jobs:
  windows-mingw:
    name: MinGW ${{ matrix.mingw-n-bits }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mingw: ["MINGW32", "MINGW64"]
        include:
          - mingw: "MINGW32"
            package: "mingw-w64-i686"
          - mingw: "MINGW64"
            package: "mingw-w64-x86_64"

    env:
      MSYSTEM: ${{ matrix.mingw }}
      CMAKE_ARGS: -DSIMDJSON_BUILD_STATIC=ON
      CMAKE_GENERATOR: MSYS Makefiles

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake -DSIMDJSON_BUILD_STATIC=ON ..
          cmake --build . --verbose
          ctest -j4 --output-on-failure -E checkperf
