name: MinGW-CI

on: push

jobs:
  windows-mingw:
    name: MinGW ${{ matrix.mingw-n-bits }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mingw-n-bits:
          - 32
          - 64
    env:
      CMAKE_ARGS: -DSIMDJSON_BUILD_STATIC=ON
      CMAKE_GENERATOR: MSYS Makefiles

    steps:
      - uses: actions/checkout@v2

      - name: Build 64-bit
        run: |
          mkdir build
          cd build
          cmake -DSIMDJSON_BUILD_STATIC=ON ..
          cmake --build . --verbose
          ctest -j4 --output-on-failure -E checkperf
