name: MinGW-CI

on: push

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      CMAKE_GENERATOR: Ninja # critical

    strategy:
      fail-fast: false
      matrix:
        name: [windows-gcc]

        include:
          - name: windows-gcc
            os: windows-latest
            compiler: gcc

    steps:
      - uses: actions/checkout@v2

      - name: Install Ninja
        shell: powershell
        run: |
          choco install -y ninja --force              # critical

      - name: Build 64-bit
        run: |
          mkdir buildx64
          cd buildx64
          cmake -DSIMDJSON_BUILD_STATIC=ON ..
          cmake --build . --verbose
          cd ..

      - name: Test 64-bit
        run: |
          cd buildx64
          ctest -j4 --output-on-failure -E checkperf
          cd ..
