name: MinGW-CI

on: push

jobs:
  windows-mingw:
    name: ${{ matrix.mingw }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mingw: ["MINGW32", "MINGW64"]
        include:
          - mingw: "MINGW32"
            package: "mingw-w64-i686"
          - mingw: "MINGW64"
            package: "mingw-w64-x86_64"

    env:
      MSYSTEM: ${{ matrix.mingw }}
      CHERE_INVOKING: 1
      CMAKE_ARGS: -DSIMDJSON_BUILD_STATIC=ON
      CMAKE_GENERATOR: MSYS Makefiles

    steps:
      - uses: actions/checkout@v2

      - name: Compiler
        run: |
          set MSYSTEM=${{ matrix.mingw }}
          gcc --version
          g++ --version

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DSIMDJSON_BUILD_STATIC=ON  -DSIMDJSON_COMPETITION=OFF -DSIMDJSON_GOOGLE_BENCHMARKS=OFF -DSIMDJSON_ENABLE_THREADS=OFF ..
          cmake --build . --verbose
          
      - name: Test
        run: |
          ctest . -R stringparsingcheck  --output-on-failure
          ctest . -R numberparsingcheck  --output-on-failure
          ctest . -R errortests  --output-on-failure
          ctest . -R integer_tests  --output-on-failure
          ctest . -R pointercheck  --output-on-failure
