name: MinGW-CI

on: push

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      CMAKE_GENERATOR: Ninja # This is critical, try ' cmake  -GNinja-DSIMDJSON_BUILD_STATIC=ON .. ' if using the command line
      CC: gcc
      CXX: g++
      BUILD_FLAGS: --verbose
      CMAKE_FLAGS: -DSIMDJSON_BUILD_STATIC=ON
      CTEST_FLAGS: -j4 --output-on-failure -E checkperf

    strategy:
      fail-fast: false
      matrix:
        name: [windows-gcc]

        include:
          - name: windows-gcc
            os: windows-2016
            compiler: gcc

          - name: windows-gcc
            os: windows-latest
            compiler: gcc

    steps: # To reproduce what is below, start a powershell with administrative rights, using scoop *is* a good idea
      - uses: actions/checkout@v2

      - name: Setup Windows
        shell: powershell
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          
          scoop install sudo --global
          sudo scoop install git --global 
          sudo scoop install ninja --global
          sudo scoop install gcc --global
          echo "::set-env name=CC::gcc"
          echo "::set-env name=CXX::g++"
          echo "::set-env name=PATH::$env:PATH"
      - name: Build and Test x64
        run: |
          mkdir build64
          cd build64
          cmake $CMAKE_FLAGS ..
          cmake --build . $BUILD_FLAGS
          ctest $CTEST_FLAGS
